name: Dev-Marshal formsflow.ai Web CD


on:
  push:
    branches:
      - dev-marshal
    paths:
      - "apps/forms-flow-ai/forms-flow-ai-web/**"
      - ".github/workflows/forms-flow-ai-web-cd-dev-marshal.yml"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev/test/prod)"
        required: true
        default: "dev"

defaults:
  run:
    shell: bash
    working-directory: ./apps/forms-flow-ai/forms-flow-ai-web

env:
  APP_NAME: "forms-flow-ai-web"
  TAG_NAME: "dev"
  BRANCH_NAME: "dev-marshal"

jobs:
  forms-flow-ai-web-cd-by-push:
    runs-on: ubuntu-20.04

    if: github.event_name == 'push' && github.repository == 'bcgov/foi-flow'
    environment:
      name: "dev"

    steps:
      - uses: actions/checkout@v2

      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${{secrets.OPENSHIFT4_LOGIN_REGISTRY}} --token=${{secrets.OPENSHIFT4_AI_SA_TOKEN}}


      - name: Tools project
        shell: bash
        run: |
          oc project ${{ secrets.OPENSHIFT4_AI_FRONTEND_REPOSITORY }}-tools

      - name: Build from ${{ env.BRANCH_NAME }} branch
        shell: bash
        run: |
          oc patch bc/${{ env.APP_NAME }} -p '{"spec":{"source":{"git":{"ref":"${{ env.BRANCH_NAME }}"}}}}'

      - name: Start Build Openshift
        shell: bash
        run: |
          oc start-build ${{ env.APP_NAME }} --wait


      - name: Tag+Deploy for ${{ env.TAG_NAME }}
        shell: bash
        run: |
          oc tag ${{ env.APP_NAME }}:latest ${{ env.APP_NAME }}:${{ env.TAG_NAME }}

      - name: Watch new rollout (trigger by image change in Openshift)
        shell: bash
        run: |
          oc rollout status dc/${{ env.APP_NAME }} -n ${{ secrets.OPENSHIFT4_AI_FRONTEND_REPOSITORY }}-${{ env.TAG_NAME }} -w

      # - name: Rocket.Chat Notification
      #   uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
      #   if: failure()
      #   with:
      #     type: ${{ job.status }}
      #     job_name: "*Auth Web Built and Deployed to ${{env.TAG_NAME}}*"
      #     channel: "#registries-bot"
      #     url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
      #     commit: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
