name: TEST FormsFlowWeb CD


on:
  push:
    branches:
      - main
      - dev-AC-212c
    paths:
      - "forms-flow-web/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev/test/prod)"
        required: true
        default: "dev"

defaults:
  run:
    shell: bash
    working-directory: ./forms-flow-web

env:
  APP_NAME: "forms-flow-web"
  TAG_NAME: "test"

jobs:
  forms-flow-web-cd-by-push:
    runs-on: ubuntu-20.04

    if: github.event_name == 'push' && github.repository == 'bcgov/foi-flow'
    environment:
      name: "dev"

    steps:
      - uses: actions/checkout@v2

      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${{secrets.OPENSHIFT4_LOGIN_REGISTRY}} --token=${{secrets.OPENSHIFT4_SA_TOKEN}}


      - name: Tools project
        shell: bash
        run: |
          oc project ${{ secrets.OPENSHIFT4_FRONTEND_REPOSITORY }}-tools

      - name: Build from dev branch
        shell: bash
        run: |
          oc patch bc/${{ env.APP_NAME }} -p '{"spec":{"source":{"contextDir":"/forms-flow-web","git":{"ref":"main"}}}}'

      - name: Start Build Openshift
        shell: bash
        run: |
          oc start-build ${{ env.APP_NAME }} --wait

      - name: Tag+Deploy for TEST
        shell: bash
        run: |
          oc tag ${{ env.APP_NAME }}:latest ${{ env.APP_NAME }}:${{ env.TAG_NAME }}

      - name: Watch new rollout (trigger by image change in Openshift)
        shell: bash
        run: |
          oc rollout status dc/${{ env.APP_NAME }} -n ${{ secrets.OPENSHIFT4_FRONTEND_REPOSITORY }}-${{ env.TAG_NAME }} -w

      # - name: Rocket.Chat Notification
      #   uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
      #   if: failure()
      #   with:
      #     type: ${{ job.status }}
      #     job_name: "*Auth Web Built and Deployed to ${{env.TAG_NAME}}*"
      #     channel: "#registries-bot"
      #     url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
      #     commit: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
